### PR TITLE
Fix to compute metrics in ensemble viewer

### LINKED ISSUE #150: EnsembleViewer cannot compute stats anymore
Ensemble viewer does not show the metric values when metric is selected.  Appears to happen for all metrics

### PR DESCRIPTION
**Pull request by dvdhoz**
Change String to String array for MetricCollection::getDateForStatistics method

Fix #150.

### CODE REVIEW

File: FIRO_TSEnsembles/src/main/java/hec/metrics/MetricCollection.java [hunk 1]
```diff
@@ -62,7 +62,8 @@ public Duration getInterval() {
     //probably need getdataforparametername.
 
     public float[] getDateForStatistic(Statistics stat){
-        int index = Arrays.asList(metric_statisticsLabel).indexOf(stat);
+        String[] splitString = metric_statisticsLabel.split(",");
```
Comment (Brennan1994) [inline FIRO_TSEnsembles/src/main/java/hec/metrics/MetricCollection.java:65]: Just checked the label for multiStatComputable and it looks like the new convention is to use a "|" to separate multiple stats in a multistat. So we should replace the "," here with the pipe.

**Review by Brennan1994 — CHANGES_REQUESTED** [review]

File: FIRO_TSEnsembles/src/main/java/hec/metrics/MetricCollection.java (hunk 1 above)
Comment (dvdhoz) [reply FIRO_TSEnsembles/src/main/java/hec/metrics/MetricCollection.java]: For the single string case, the pipe operator doesn't seem to work.  Add both the pipe operator and comma as possible separator options

**Review by Brennan1994 — APPROVED** [review]
